name: Snyk Security Scan

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -la
        working-directory: .

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: .

      - name: Check Gradle version
        run: ./gradlew --version
        working-directory: .

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Snyk
        run: npm install -g snyk@latest

      - name: Run Snyk test
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: .